### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by IlhanSeven** [node-modbus/stream#31]
Hi Diego,

Thanks again for your work. Is below a drop of established connection? Is there something that can be enabled to automatically establish the connection again? If not, what is the best way to reestablish the connection. 

Thank you for your help.

Ilhan

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:659:25)
Emitted 'error' event at:
    at Transport.<anonymous> (/home/ilhans/tools/grid-tester/node_modules/modbus-stream/lib/stream.js:36:10)
    at Transport.emit (events.js:182:13)
    at Transport.<anonymous> (/home/ilhans/tools/grid-tester/node_modules/modbus-stream/lib/transport/transport.js:21:8)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by dresende** [comment]
Hi Ilhan,

The `ECONNRESET` means something in the network between the 2 hosts dropped the connection because of some error (a router or one of the hosts does not know the connection or lost network connection, ..). You should listen for the `error` event and do something about (print it maybe).

Reconnecting should be similar to what you perhaps do in the `mysql` module. Delete the connection variable, create a new one and reconnect. It's not recommended to try to reuse a connection that is in an unknown state. What I usually do is, when I need to use the connection, call a function that will return me the connection. That function is responsible for having a "working" connection.

```js
let connection_handle = null;

function get_connection(next) {
    if (connection_handle) {
        return next(null, connection_handle);
    }

    modbus.tcp.connect(12345, { debug: null }, (err, connection) => {
        if (err) return next(err);

        connection_handle = connection;

        connection_handle.on("error", (err) => {
            console.log("connection error", err);

            delete connection_handle;
        });

        return next(null, connection_handle);
    });
}
```
